replicaCount: 1

image:
  repository: ghcr.io/gokayybaz/bazusop
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 8080

secrets:
  existingSecret: bazusop-secrets
  databaseURLKey: database-url
  enrollmentTokenKey: enrollment-token
  operatorTokenKey: operator-token

timescale:
  enabled: false

tls:
  enabled: false
  existingSecret: ""
  certificateKey: tls.crt
  privateKeyKey: tls.key

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: bazusop.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: ScheduleAnyway

nodeSelector: {}
tolerations: []
affinity: {}
